### ISSUE TITLE
need the branch for dble 2.19.03/lts

### ISSUE THREAD

**Issue by Lordess** [actiontech/dble-docs-cn#150]
[dble 2.19.03/lts](https://github.com/actiontech/dble/tree/2.19.03/lts) has an  extraordinary lifetime. Thus, we ask the doc project to have a specified branch for it.

**Comment by yanhuqing666** [comment]
is this enough?  https://github.com/actiontech/dble-docs-cn/tree/2.19.03.0/tag

**Comment by Lordess** [comment]
Not yet. 

Because we are going to add some experiemental features on dble 2.19.03/lts. Also there are some fixes of doc need to migrated, i.e.  f3501d6...5f6e61a. So I prefer to a modifiable branch for sequential maintaince.

**Comment by yanhuqing666** [comment]
https://github.com/actiontech/dble-docs-cn/tree/2.19.03/lts

**Comment by Lordess** [comment]
Thx a lot
