### ISSUE TITLE
`groupConcatMaxLen` needs to be added to the bootstrap.cnf configuration documentation

### ISSUE THREAD

**Issue by asiroliu** [actiontech/dble-docs-cn#292]
When the value of group_concat_max_len on the backend mysql instance is changed to custom vaule, it can be adapted by configuring `groupConcatMaxLe` in the bootstrap.cnf file. But it is not documented in bootstrap.cnf's documentation.

Please check if there are any other missing items.

**Comment by quexiuping** [comment]
verified on 3.21.06 3.21.10 3.22.01
